### ISSUE TITLE
Not handle error event

### ISSUE THREAD

**Issue by evilebottnawi** [nfroidure/SVGPathData#15] opened 2016-11-07 19:53 UTC
/cc @nfroidure 
In this line https://github.com/nfroidure/SVGPathData/blob/master/src/SVGPathData.js#L114
Error:
```shell
SyntaxError: Unexpected character "N" at index 2.
    at SVGPathDataParser._transform (/path/to/node_modules/svg-pathdata/src/SVGPathDataParser.js:461:28)
    at SVGPathDataParser.Transform._read (/path/to/node_modules/svg-pathdata/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at SVGPathDataParser.Transform._write (/path/to/node_modules/svg-pathdata/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/path/to/node_modules/svg-pathdata/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/path/to/node_modules/svg-pathdata/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at SVGPathDataParser.Writable.write (/path/to/node_modules/svg-pathdata/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Function.SVGPathData.parse (/path/to/node_modules/svg-pathdata/src/SVGPathData.js:124:10)
    at new SVGPathData (/path/to/node_modules/svg-pathdata/src/SVGPathData.js:4:31)
    at /path/to/node_modules/svgicons2svgfont/src/index.js:341:20
    at Array.forEach (native)
    at SVGIcons2SVGFontStream._svgIcons2SVGFontStreamFlush [as _flush] (/path/to/node_modules/svgicons2svgfont/src/index.js:313:12)
    at SVGIcons2SVGFontStream.<anonymous> (/path/to/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at SVGIcons2SVGFontStream.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at SVGIcons2SVGFontStream.emit (events.js:185:7)
    at prefinish (/path/to/node_modules/readable-stream/lib/_stream_writable.js:475:12)
    at finishMaybe (/path/to/node_modules/readable-stream/lib/_stream_writable.js:483:7)
    at afterWrite (/path/to/node_modules/readable-stream/lib/_stream_writable.js:367:3)
    at onwrite (/path/to/node_modules/readable-stream/lib/_stream_writable.js:358:9)
    at WritableState.onwrite (/path/to/node_modules/readable-stream/lib/_stream_writable.js:122:5)
    at afterTransform (/path/to/node_modules/readable-stream/lib/_stream_transform.js:81:3)
    at TransformState.afterTransform (/path/to/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at SAXStream.svgicons2svgfontSaxEnbCb (/path/to/node_modules/svgicons2svgfont/src/index.js:259:7)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:185:7)
    at SAXParser.SAXStream._parser.onend (/path/to/node_modules/sax/lib/sax.js:190:10)
    at emit (/path/to/node_modules/sax/lib/sax.js:640:35)
    at end (/path/to/node_modules/sax/lib/sax.js:683:5)
    at SAXParser.end (/path/to/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/path/to/node_modules/sax/lib/sax.js:248:18)
```

I am use https://github.com/nfroidure/svgicons2svgfont package in my package https://github.com/itgalaxy/webfont. If i run watch and use `normalize: true` and have one bad svg icon (empty file), other icons is good, i got this error.

**Comment by nfroidure** [comment] 2016-11-08 07:10
This exception is probably raised by the fact you are providing a SVG file with invalid path data (probably a string begginning by N). I think you should avoid sending empty SVG files to this module.

That said, i would need more feedback in order to support you in solving this issue. A sample project reproducing the behavior with a minimal set of icons would be the best.

**Comment by evilebottnawi** [comment] 2016-11-08 09:20
@nfroidure thanks for answer, if I find the time to'll create an example

**Comment by nfroidure** [comment] 2017-03-04 17:54
Closing since no move for a long time.

**Closed by nfroidure** 2017-03-04 17:54 UTC
