### ISSUE TITLE
Latest release breaks one of my SVG font icons

### ISSUE THREAD

**Issue by omarmeky** [nfroidure/SVGPathData#17] opened 2016-11-30 00:12 UTC
I am generating font icons from SVGs using [gulp-iconfont](https://github.com/nfroidure/gulp-iconfont) which indirectly depends on this module. After the latest release, the following SVG image ceases to properly generate a font. Note that other SVGs are still working. Any idea(s) what change(s) may have caused this? Note that explicitly depending on the `1.0.3` version of this package fixes my issue.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="800px" height="800px" viewBox="0 0 800 800" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 3.8.3 (29802) - http://www.bohemiancoding.com/sketch -->
    <title>icon_appt_line</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Icon-800" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="icon_appt_line" fill="#FFFFFF">
            <g id="icon_appt+slice">
                <g id="icon_appt_line" transform="translate(75.000000, 50.000000)">
                    <path d="M62.0679012,645.644217 L62.0679012,645.644217 L62.0679012,665.641498 C62.0679012,665.598192 62.1125446,665.642857 62.1053449,665.642857 L586.042803,665.642857 C586.189143,665.642857 586.080247,665.752257 586.080247,665.641498 L586.080247,645.644217 C586.080247,645.687523 586.035604,645.642857 586.042803,645.642857 L62.1053449,645.642857 C61.9590049,645.642857 62.0679012,645.533457 62.0679012,645.644217 L62.0679012,645.644217 Z M34.5679012,645.644217 C34.5679012,630.455635 46.661397,618.142857 62.1053449,618.142857 L586.042803,618.142857 C601.251313,618.142857 613.580247,630.527582 613.580247,645.644217 L613.580247,665.641498 C613.580247,680.830079 601.486751,693.142857 586.042803,693.142857 L62.1053449,693.142857 C46.8968347,693.142857 34.5679012,680.758133 34.5679012,665.641498 L34.5679012,645.644217 L34.5679012,645.644217 Z" id="Rectangle-1"></path>
                    <path d="M27.5,224.665783 L27.5,224.665783 L27.5,619.048503 C27.5,619.081412 27.5157852,619.096768 27.4361296,619.096768 L620.712019,619.096768 C620.608638,619.096768 620.648148,619.058449 620.648148,619.048503 L620.648148,224.665783 C620.648148,224.632874 620.632363,224.617517 620.712019,224.617517 L27.4361296,224.617517 C27.5395106,224.617517 27.5,224.655836 27.5,224.665783 L27.5,224.665783 Z M0,224.665783 C0,209.938678 12.3688579,198 27.4361296,198 L620.712019,198 C635.864575,198 648.148148,209.975276 648.148148,224.665783 L648.148148,619.048503 C648.148148,633.775608 635.77929,645.714286 620.712019,645.714286 L27.4361296,645.714286 C12.2835736,645.714286 0,633.73901 0,619.048503 L0,224.665783 L0,224.665783 Z" id="Rectangle-1"></path>
                    <path d="M0,81.7816072 C0,66.5960448 12.3152915,54.2857143 27.5006313,54.2857143 L620.647517,54.2857143 C635.835696,54.2857143 648.148148,66.593211 648.148148,81.7816072 L648.148148,228.571429 L0,228.571429 L0,81.7816072 Z M132.510288,54.2857143 L220.110971,54.2857143 L220.110971,139.346835 C220.110971,163.542184 200.506209,183.15639 176.31063,183.15639 C152.120369,183.15639 132.510288,163.548672 132.510288,139.346835 L132.510288,54.2857143 Z M426.337449,54.2857143 L513.938132,54.2857143 L513.938132,139.346835 C513.938132,163.542184 494.33337,183.15639 470.13779,183.15639 C445.94753,183.15639 426.337449,163.548672 426.337449,139.346835 L426.337449,54.2857143 Z" id="Combined-Shape"></path>
                    <path d="M152.674897,26.0441126 C152.674897,13.2383028 163.060428,2.85714286 176.013105,2.85714286 L178.307883,2.85714286 C191.197219,2.85714286 201.646091,13.1677246 201.646091,26.0441126 L201.646091,136.81303 C201.646091,149.61884 191.26056,160 178.307883,160 L176.013105,160 C163.123769,160 152.674897,149.689418 152.674897,136.81303 L152.674897,26.0441126 L152.674897,26.0441126 Z" id="Rectangle-2"></path>
                    <path d="M446.502058,23.1869698 C446.502058,10.38116 456.887588,0 469.840266,0 L472.135043,0 C485.024379,0 495.473251,10.3105818 495.473251,23.1869698 L495.473251,133.955887 C495.473251,146.761697 485.08772,157.142857 472.135043,157.142857 L469.840266,157.142857 C456.950929,157.142857 446.502058,146.832275 446.502058,133.955887 L446.502058,23.1869698 L446.502058,23.1869698 Z" id="Rectangle-2"></path>
                    <g id="Group" transform="translate(115.226337, 288.571429)">
                        <rect id="Rectangle-33" x="0" y="0" width="100.823045" height="100" rx="13.75"></rect>
                        <path d="M177.686214,13.7472003 L177.686214,13.7472003 L177.686214,86.2527997 C177.686214,83.208477 175.227135,80.75 172.191167,80.75 L245.504306,80.75 C242.473281,80.75 240.009259,83.2130217 240.009259,86.2527997 L240.009259,13.7472003 C240.009259,16.791523 242.468339,19.25 245.504306,19.25 L172.191167,19.25 C175.222192,19.25 177.686214,16.7869783 177.686214,13.7472003 L177.686214,13.7472003 Z M158.436214,13.7472003 C158.436214,6.1548312 164.591375,0 172.191167,0 L245.504306,0 C253.100957,0 259.259259,6.16117766 259.259259,13.7472003 L259.259259,86.2527997 C259.259259,93.8451688 253.104098,100 245.504306,100 L172.191167,100 C164.594516,100 158.436214,93.8388223 158.436214,86.2527997 L158.436214,13.7472003 L158.436214,13.7472003 Z" id="Rectangle-33"></path>
                        <path d="M336.122428,13.7472003 L336.122428,13.7472003 L336.122428,86.2527997 C336.122428,83.208477 333.663349,80.75 330.627381,80.75 L403.94052,80.75 C400.909495,80.75 398.445473,83.2130217 398.445473,86.2527997 L398.445473,13.7472003 C398.445473,16.791523 400.904553,19.25 403.94052,19.25 L330.627381,19.25 C333.658406,19.25 336.122428,16.7869783 336.122428,13.7472003 L336.122428,13.7472003 Z M316.872428,13.7472003 C316.872428,6.1548312 323.027589,0 330.627381,0 L403.94052,0 C411.537171,0 417.695473,6.16117766 417.695473,13.7472003 L417.695473,86.2527997 C417.695473,93.8451688 411.540312,100 403.94052,100 L330.627381,100 C323.03073,100 316.872428,93.8388223 316.872428,86.2527997 L316.872428,13.7472003 L316.872428,13.7472003 Z" id="Rectangle-33"></path>
                        <path d="M19.25,165.175772 L19.25,165.175772 L19.25,237.681371 C19.25,234.637048 16.7909207,232.178571 13.7549532,232.178571 L87.068092,232.178571 C84.0370672,232.178571 81.5730453,234.641593 81.5730453,237.681371 L81.5730453,165.175772 C81.5730453,168.220094 84.0321246,170.678571 87.068092,170.678571 L13.7549532,170.678571 C16.785978,170.678571 19.25,168.21555 19.25,165.175772 L19.25,165.175772 Z M0,165.175772 C0,157.583403 6.15516106,151.428571 13.7549532,151.428571 L87.068092,151.428571 C94.6647429,151.428571 100.823045,157.589749 100.823045,165.175772 L100.823045,237.681371 C100.823045,245.27374 94.6678842,251.428571 87.068092,251.428571 L13.7549532,251.428571 C6.15830233,251.428571 0,245.267394 0,237.681371 L0,165.175772 L0,165.175772 Z" id="Rectangle-33"></path>
                        <path d="M177.686214,165.175772 L177.686214,165.175772 L177.686214,237.681371 C177.686214,234.637048 175.227135,232.178571 172.191167,232.178571 L245.504306,232.178571 C242.473281,232.178571 240.009259,234.641593 240.009259,237.681371 L240.009259,165.175772 C240.009259,168.220094 242.468339,170.678571 245.504306,170.678571 L172.191167,170.678571 C175.222192,170.678571 177.686214,168.21555 177.686214,165.175772 L177.686214,165.175772 Z M158.436214,165.175772 C158.436214,157.583403 164.591375,151.428571 172.191167,151.428571 L245.504306,151.428571 C253.100957,151.428571 259.259259,157.589749 259.259259,165.175772 L259.259259,237.681371 C259.259259,245.27374 253.104098,251.428571 245.504306,251.428571 L172.191167,251.428571 C164.594516,251.428571 158.436214,245.267394 158.436214,237.681371 L158.436214,165.175772 L158.436214,165.175772 Z" id="Rectangle-33"></path>
                        <path d="M336.122428,165.175772 L336.122428,165.175772 L336.122428,237.681371 C336.122428,234.637048 333.663349,232.178571 330.627381,232.178571 L403.94052,232.178571 C400.909495,232.178571 398.445473,234.641593 398.445473,237.681371 L398.445473,165.175772 C398.445473,168.220094 400.904553,170.678571 403.94052,170.678571 L330.627381,170.678571 C333.658406,170.678571 336.122428,168.21555 336.122428,165.175772 L336.122428,165.175772 Z M316.872428,165.175772 C316.872428,157.583403 323.027589,151.428571 330.627381,151.428571 L403.94052,151.428571 C411.537171,151.428571 417.695473,157.589749 417.695473,165.175772 L417.695473,237.681371 C417.695473,245.27374 411.540312,251.428571 403.94052,251.428571 L330.627381,251.428571 C323.03073,251.428571 316.872428,245.267394 316.872428,237.681371 L316.872428,165.175772 L316.872428,165.175772 Z" id="Rectangle-33"></path>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

**Comment by nfroidure** [comment] 2016-11-30 08:50
Probably a regression i won't have time to look at it quickly though. Would help it you could add a failing test to the lib.

On the other hand your SVG seems really complicated and has a lot of SVG paths and groups with transformations. Simplifying it should solve your problem in the meanwhile.

Finally, since gorups and transformations are involved, the problem may sit in another module, svgicons2svgfont deals with transformations and path gourping. It is possible that the SVGPathData fix has revealed a but in this module.

**Comment by pguimera** [comment] 2016-12-15 15:10
Hey, not sure if it helps, but I don't really think the problem lies with the complexity of the SVG rather than with the fill rule `fill-rule="evenodd"` and the `woff` and `woff2` formats.

**Comment by nfroidure** [comment] 2017-07-15 11:23
Closing since the issue is very old (2 major versions since) and does not contain enough feedback to help resolve it.

**Closed by nfroidure** 2017-07-15 11:23 UTC
Labels: bug
